export const ADATOK = [
    {
        Nev: "Temerario",
        Kep: "kepek/1.webp",
        Bevezetes:"A Temerario egy új evolúciós lépést jelent a Lamborghini teljes hibridizáció felé vezető útján. A Sant'Agata Bolognese második HPEV (High Performance Electrified Vehicle) forradalmi formatervezési, technológiai és bravúros. A bi-turbós V8-as motor a három elektromos motorral együttműködve új határt hoz létre a teljesítményben és a vezetési érzelmekben, amelyek újradefiniálják a szupersportkocsik szabványait.",
        Teljesitmeny:"920 CV",
        Sebesség:"343 km/h",
        Gyorsulas:"2,7 s",
        Reszletek:"A Lamborghini bemutatja a Temerario-t, a Sant'Agata bolognesei székhelyű márka történetében az első szupersportautót, amelyet V8-as ikerturbós motorral és három villanymotorral szereltek fel, 920 CV összteljesítménnyel. Ez a második jármű a HPEV (High Performance Electrified Vehicle) kínálatában, amely a kategóriájában egyedülálló teljesítményének és kényelmének köszönhetően a vezetési élmény tekintetében a csúcson áll. Új tervezési stíluskoncepciókat tartalmaz, miközben soha nem látott testreszabási lehetőségeket és csatlakozási tartalmat kínál.",
        Dollar_ar:"400 000 dollár",
        Ar:"495977300,00 FT",
        Szerkeszheto:false,

    },
    {
        Nev: "Revuelto",
        Kep: "kepek/2.webp",
        Bevezetes:"A Revuelto egy új korszak kezdete a Lamborghini számára, aki a hibridizációs technológia erejét kihasználva megalkotta az első HPEV-t (High Performance Electrified Vehicle). A fenntarthatóság és az erőteljes teljesítmény iránti igényre reagálva a Lamborghini Revuelto minden paradigmát újraír, és mindenki képzeletét felülmúló technikai remekművet képvisel. Az ikonikus V12-es motor új életre talál ebben a futurisztikus autóipari mesterműben, amely páratlan teljesítményt és vezetési érzelmeket biztosít.",
        Teljesitmeny:"1015 CV",
        Sebesség:"350  km/h",
        Gyorsulas:"2.5 s",
        Reszletek:"Közvetlenül a márka fennállásának 60. évfordulója előtt a Lamborghini bemutatta a Revueltót, az első HPEV (High Performance Electrified Vehicle) hibrid szupersportkocsit. A Revueltóval a Lamborghini új mércét állított fel a teljesítmény, a fedélzeti technológia és a vezetési élmény terén. A Revuelto nyújtotta végső izgalmat az 1015 CV összteljesítményű hajtásláncnak köszönheti, amely egy vadonatúj, 12 hengeres belső égésű motor erejét három nagy sűrűségű villanymotorral és egy úttörő keresztirányú duplakuplungos e-váltóval ötvözi. A hibridizáció erejét arra használják fel, hogy a teljesítményt és az érzelmek felhajtását soha nem látott szintre emeljék.",
        Dollar_ar:"608 358 dollár",
        Ar:"215522684,48 FT",
        Szerkeszheto:false,

    },
    {
        Nev: "Urus SE",
        Kep: "kepek/3.webp",
        Bevezetes:"A Lamborghini Urus a világ első Super Sport Utility Vehicle, ahol az exkluzivitás, a sportosság és a teljesítmény találkozik kényelemmel és sokoldalúsággal. Kategóriájában a legjobb menetdinamikát és összetéveszthetetlen eleganciát kínál a dizájnban. Az Urus a többféle lélek jellemzőit testesíti meg: sportos, elegáns és off-road. A sorozat a jövőre irányul, új korszakot nyitva a luxus Super SUV első PHEV (plug-in hibrid elektromos jármű) változatával. Páratlan teljesítményével, szórakoztató vezetési élményével és úttörő szellemével a Lamborghini Urus minden, csak nem tipikus.",
        Teljesitmeny:"800 CV",
        Sebesség:"312 km/h",
        Gyorsulas:"3,4 s",
        Reszletek:"Az Urus SE az Automobili Lamborghini teljes hibridizáció felé vezető útjának következő lépése. A luxus Super SUV első PHEV (plug-in hibrid elektromos jármű) változataként az SE új mércét állít fel az egész szegmens számára kényelem, teljesítmény, hatékonyság, károsanyag-kibocsátás és vezetési élmény tekintetében. A termikus és elektromos hajtáslánc 800 CV-os teljesítménnyel büszkélkedhet, és hozzájárul az elképesztő, 80%-os kibocsátáscsökkentéshez. Az Urus SE erővel, sebességgel, egyedi vezetési módokkal és továbbfejlesztett dinamikával büszkélkedhet, így a jövő forradalmi járműve.",
        Dollar_ar:"245 000 dollár",
        Ar:"86796027,50",
        Szerkeszheto:false,

    },
    {
        Nev: "Huracán Sterrato",
        Kep: "kepek/4.webp",
        Bevezetes:"A múltunkból megtanultuk a tökéletességet. Így született meg a Lamborghini Huracán első modellje. Több teljesítmény, több irányítás, több innováció. A Huracán erős V10-es motorral és a legújabb technológiákkal van felszerelve, hogy a legjobb teljesítményt nyújtsa. Úgy tervezték, hogy garantálja a legjobb teljesítményt és irányíthatóságot bármilyen vezetési körülmény között, könnyű a végletekig vinni, nem is beszélve a rendkívül szórakoztató technológiáról, mint például a Lamborghini Doppia Frizione (LDF) kettős tengelykapcsolós sebességváltó és az elektronikusan vezérelt négykerék-hajtás. . Élvezze a valaha volt legjobb vezetési élményt. Fedezze fel az összes Lamborghini Huracán modellt.",
        Teljesitmeny:"610 CV",
        Sebesség:"260 km/h",
        Gyorsulas:"3,4s",
        Reszletek:"Az első a maga nemében, a Huracán Sterrato a vezetési élmény új határait fedezi fel, és úgy tervezték, hogy az aszfalt végén eltolja a borítékot. A szupersportkocsi az LDVI (Lamborghini Integrated Vehicle Dynamics) rendszer egy dedikált iterációjával van felszerelve, amely speciális Strada és Sport kalibrációkat tartalmaz, valamint bevezeti a Rally módot. Mint egy műalkotás, az innováció élvonalát képviseli: a radikálisan új módon elképzelt szupersportkocsi koncepciót. ",
        Dollar_ar:"503 949 dollár",
        Ar:"178533760,26 FT",
        Szerkeszheto:false,
    },
    {
        Nev: "Limited Series Sián FKP 37",
        Kep: "kepek/4.webp",
        Bevezetes:"A Limited Series Lamborghini a legexkluzívabb, limitált kiadások, amelyek kis számú és válogatott ügyfél számára alkalmasak. A limitált sorozatú modellek, amelyek valóban a szuperautók legkorszerűbb szintjét képviselik, a Lamborghini legmagasabb szellemiségét fejezik ki minden tekintetben. Valójában a tervezés és a technológia területén elérhető legfejlettebb funkciókkal vannak felszerelve.",
        Teljesitmeny:"819 CV",
        Sebesség:"355  km/h",
        Gyorsulas:"2,8 s",
        Reszletek:"A Sián FKP 37 az első szupersportkocsi, amelyet V12-es motor és szuperkondenzátorokon alapuló hibrid technológia hajt. Erőteljes V12-es motorja elektromos lökettel párosulva a tervezés és a technológia páratlan gyöngyszemét hozza létre. A Sián – bolognai villám – egy név, amely megragadja az autó igazi karakterét, mindenekelőtt a sebességét, amely meghaladja a 350 km/h-t.",
        Dollar_ar:"5 913 648 dollár",
        Ar:"2095025120,14 FT",
        Szerkeszheto:false,

    },
    
]